name: Update Dependencies

on:
  schedule:
    # Run weekly on Sundays at 6 AM UTC
    - cron: '0 6 * * 0'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Update dependencies
      run: |
        # Update dependencies to latest versions
        uv sync --upgrade
        
        # Check if there are any changes
        if git diff --quiet uv.lock; then
          echo "No dependency updates available"
          echo "has_updates=false" >> $GITHUB_OUTPUT
        else
          echo "Dependencies updated"  
          echo "has_updates=true" >> $GITHUB_OUTPUT
        fi
      id: update
    
    outputs:
      has_updates: ${{ steps.update.outputs.has_updates }}

  test:
    if: needs.update-dependencies.outputs.has_updates == 'true'
    needs: update-dependencies
    uses: ./.github/workflows/ci.yml

  create-pr:
    if: needs.update-dependencies.outputs.has_updates == 'true'
    needs: [update-dependencies, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "chore: update dependencies"
        body: |
          ## Automated Dependency Update
          
          This PR updates project dependencies to their latest versions.
          
          ### Changes
          - Updated `uv.lock` with latest dependency versions
          
          ### Testing
          - ✅ All tests pass with updated dependencies
          - ✅ Code style checks pass
          
          This PR was created automatically by the dependency update workflow.
        branch: dependency-updates
        delete-branch: true
